"use client";

import { useState } from "react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { RecommendationCard } from "@/components/recommendation-card";
import type { ValidatedRecommendation, ValidatedRecommendationResponse } from "@/lib/types";

interface CollapsibleSectionProps {
  title: string;
  count: number;
  badgeVariant: "destructive" | "secondary";
  items: ValidatedRecommendation[];
  type: "cut" | "addition" | "mana_base";
  defaultOpen?: boolean;
}

function CollapsibleSection({
  title,
  count,
  badgeVariant,
  items,
  type,
  defaultOpen = true,
}: CollapsibleSectionProps) {
  const [open, setOpen] = useState(defaultOpen);

  if (items.length === 0) return null;

  return (
    <section className="flex flex-col gap-3">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex cursor-pointer items-center gap-2 select-none"
      >
        <span
          className="text-muted-foreground transition-transform duration-200"
          style={{
            display: "inline-block",
            transform: open ? "rotate(180deg)" : "rotate(0deg)",
          }}
        >
          ▾
        </span>
        <h3 className="text-sm font-semibold">{title}</h3>
        <Badge variant={badgeVariant} className="text-[10px]">
          {count}
        </Badge>
      </button>
      {open && (
        <div className="grid gap-3 sm:grid-cols-2">
          {items.map((rec, i) => (
            <RecommendationCard key={i} rec={rec} type={type} />
          ))}
        </div>
      )}
    </section>
  );
}

interface RecommendationsDisplayProps {
  data: ValidatedRecommendationResponse;
}

export function RecommendationsDisplay({ data }: RecommendationsDisplayProps) {
  const totalSuggestions =
    data.cuts.length + data.additions.length + data.mana_base.length;

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>Recommendations</CardTitle>
            <CardDescription>
              AI-generated suggestions based on your deck analysis
            </CardDescription>
          </div>
          <Badge variant="secondary">{totalSuggestions} suggestions</Badge>
        </div>
      </CardHeader>
      <CardContent className="flex flex-col gap-6">
        {/* General notes */}
        {data.general_notes && (
          <div className="rounded-lg bg-muted/50 p-4">
            <p className="text-sm leading-relaxed">{data.general_notes}</p>
          </div>
        )}

        <CollapsibleSection
          title="Suggested Cuts"
          count={data.cuts.length}
          badgeVariant="destructive"
          items={data.cuts}
          type="cut"
        />

        <CollapsibleSection
          title="Suggested Additions"
          count={data.additions.length}
          badgeVariant="secondary"
          items={data.additions}
          type="addition"
        />

        <CollapsibleSection
          title="Mana Base"
          count={data.mana_base.length}
          badgeVariant="secondary"
          items={data.mana_base}
          type="mana_base"
        />

        {/* Disclaimer */}
        <p className="text-[11px] text-muted-foreground">
          Suggestions are generated by Gemini Flash and validated against
          Scryfall. Recent sets may be underrepresented. Price data is
          approximate.
        </p>
      </CardContent>
    </Card>
  );
}
