"use client";

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { RecommendationCard } from "@/components/recommendation-card";
import type { ValidatedRecommendationResponse } from "@/lib/types";

interface RecommendationsDisplayProps {
  data: ValidatedRecommendationResponse;
}

export function RecommendationsDisplay({ data }: RecommendationsDisplayProps) {
  const totalSuggestions =
    data.cuts.length + data.additions.length + data.mana_base.length;

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>Recommendations</CardTitle>
            <CardDescription>
              AI-generated suggestions based on your deck analysis
            </CardDescription>
          </div>
          <Badge variant="secondary">{totalSuggestions} suggestions</Badge>
        </div>
      </CardHeader>
      <CardContent className="flex flex-col gap-6">
        {/* General notes */}
        {data.general_notes && (
          <div className="rounded-lg bg-muted/50 p-4">
            <p className="text-sm leading-relaxed">{data.general_notes}</p>
          </div>
        )}

        {/* Cuts */}
        {data.cuts.length > 0 && (
          <section className="flex flex-col gap-3">
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-semibold">Suggested Cuts</h3>
              <Badge variant="destructive" className="text-[10px]">
                {data.cuts.length}
              </Badge>
            </div>
            <div className="grid gap-3 sm:grid-cols-2">
              {data.cuts.map((rec, i) => (
                <RecommendationCard key={i} rec={rec} type="cut" />
              ))}
            </div>
          </section>
        )}

        {data.cuts.length > 0 && data.additions.length > 0 && <Separator />}

        {/* Additions */}
        {data.additions.length > 0 && (
          <section className="flex flex-col gap-3">
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-semibold">Suggested Additions</h3>
              <Badge variant="secondary" className="text-[10px]">
                {data.additions.length}
              </Badge>
            </div>
            <div className="grid gap-3 sm:grid-cols-2">
              {data.additions.map((rec, i) => (
                <RecommendationCard key={i} rec={rec} type="addition" />
              ))}
            </div>
          </section>
        )}

        {data.mana_base.length > 0 && (
          <>
            <Separator />
            <section className="flex flex-col gap-3">
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-semibold">Mana Base</h3>
                <Badge variant="secondary" className="text-[10px]">
                  {data.mana_base.length}
                </Badge>
              </div>
              <div className="grid gap-3 sm:grid-cols-2">
                {data.mana_base.map((rec, i) => (
                  <RecommendationCard key={i} rec={rec} type="mana_base" />
                ))}
              </div>
            </section>
          </>
        )}

        {/* Disclaimer */}
        <p className="text-[11px] text-muted-foreground">
          Suggestions are generated by Gemini Flash and validated against
          Scryfall. Recent sets may be underrepresented. Price data is
          approximate.
        </p>
      </CardContent>
    </Card>
  );
}
